const WEATHER_API = "WEATHER_API";
const ADD_FAVORITE_CITYS = "ADD_FAVORITE_CITYS";
const REMOVE_FAVORITE_CITY = "REMOVE_FAVORITE_CITY";
const CHECK_CITY = "CHECK_CITY";
const REMOVE_CITY = "REMOVE_CITY";
const ISLOADING = "ISLOADING";

export {
  WEATHER_API,
  ADD_FAVORITE_CITYS,
  REMOVE_FAVORITE_CITY,
  CHECK_CITY,
  REMOVE_CITY,
  ISLOADING,
};
